### ISSUE TITLE
[Feature Request]: Toast Component supports position options

### ISSUE THREAD

**Issue by Flower-F** [hippy-contrib/hippy_ui_react#1]
Provide options to customize the vertical position of toast component like ant-design.

<img width="898" alt="企业微信截图_9d3875e1-f865-4b29-8b0c-a403a8e37779" src="https://github.com/hippy-contrib/hippy_ui_react/assets/78215016/bb4deadc-f4d6-4d1e-ae62-9fd30117c293">

https://mobile.ant.design/zh/components/toast

**Comment by linjinze999** [comment]
暂未有相关设计规范，已提供自定义`style`能力满足述求：https://hippy-contrib.github.io/hippy_ui_react/#/%E7%BB%84%E4%BB%B6/Toast%20%E6%8F%90%E7%A4%BA
